server:
  port = 8080

spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  tengxun:
    SecretId = AKIDwlikjZDfuwjS4SbTIyQdcUM2VqwyudGh
    SecretKey = LSIt9E5fz3tTnu3xb0EExRijTxc3D7kS
    region = ap-shanghai
    bucketName = cos-for-scd-1312783961
    url = https://cos-for-scd-1312783961.cos-website.ap-shanghai.myqcloud.com/